const WORDS = {
    english: {
        easy: [ // Ünite 1-2-3
            { tr: 'ambulans', en: 'ambulance' },
            { tr: 'balon', en: 'balloon' },
            { tr: 'bisküvi', en: 'biscuit' },
            { tr: 'kafe', en: 'cafe' },
            { tr: 'pasta', en: 'cake' },
            { tr: 'kamp', en: 'camp' },
            { tr: 'doktor', en: 'doctor' },
            { tr: 'elektronik posta', en: 'e-mail' },
            { tr: 'elektrik', en: 'electrics' },
            { tr: 'garaj', en: 'garage' },
            { tr: 'otel', en: 'hotel' },
            { tr: 'internet', en: 'internet' },
            { tr: 'dizüstü bilgisayar', en: 'laptop' },
            { tr: 'limon', en: 'lemon' },
            { tr: 'mikrofon', en: 'microphone' },
            { tr: 'not', en: 'note' },
            { tr: 'ofis', en: 'office' },
            { tr: 'piknik', en: 'picnic' },
            { tr: 'kısa sınav', en: 'quiz' },
            { tr: 'radyo', en: 'radio' },
            { tr: 'salata', en: 'salad' },
            { tr: 'sandviç', en: 'sandwich' },
            { tr: 'spor', en: 'sport' },
            { tr: 'durmak', en: 'stop' },
            { tr: 'süpermarket', en: 'supermarket' },
            { tr: 'telefon', en: 'telephone' },
            { tr: 'televizyon', en: 'television' },
            { tr: 'domates', en: 'tomato' },
            { tr: 'tren', en: 'train' },
            { tr: 'kelime', en: 'word' },
            { tr: 'üniversite', en: 'university' },
            { tr: 'vanilya', en: 'vanilla' },
            { tr: 'video', en: 'video' },
            { tr: 'yoğurt', en: 'yoghurt' },
            { tr: 'sabah', en: 'morning' },
            { tr: 'öğleden sonra', en: 'afternoon' },
            { tr: 'akşam', en: 'evening' },
            { tr: 'gece', en: 'night' },
            { tr: 'sınıf', en: 'classroom' },
            { tr: 'kapı', en: 'door' }
        ],
        medium: [ // Ünite 4-5-6-7
            { tr: 'sayılar', en: 'numbers' },
            { tr: 'renkler', en: 'colors' },
            { tr: 'kırmızı', en: 'red' },
            { tr: 'mavi', en: 'blue' },
            { tr: 'yeşil', en: 'green' },
            { tr: 'sarı', en: 'yellow' },
            { tr: 'siyah', en: 'black' },
            { tr: 'beyaz', en: 'white' },
            { tr: 'kahverengi', en: 'brown' },
            { tr: 'turuncu', en: 'orange' },
            { tr: 'mor', en: 'purple' },
            { tr: 'pembe', en: 'pink' },
            { tr: 'oyun alanı', en: 'playground' },
            { tr: 'salıncak', en: 'swing' },
            { tr: 'kaydırak', en: 'slide' },
            { tr: 'top', en: 'ball' },
            { tr: 'ip', en: 'rope' },
            { tr: 'koşmak', en: 'run' },
            { tr: 'zıplamak', en: 'jump' },
            { tr: 'oynamak', en: 'play' },
            { tr: 'vücut', en: 'body' },
            { tr: 'baş', en: 'head' },
            { tr: 'göz', en: 'eye' },
            { tr: 'kulak', en: 'ear' },
            { tr: 'burun', en: 'nose' },
            { tr: 'ağız', en: 'mouth' },
            { tr: 'el', en: 'hand' },
            { tr: 'kol', en: 'arm' },
            { tr: 'bacak', en: 'leg' },
            { tr: 'ayak', en: 'foot' }
        ],
        hard: [ // Ünite 8-9-10
            { tr: 'evcil hayvan', en: 'pet' },
            { tr: 'kedi', en: 'cat' },
            { tr: 'köpek', en: 'dog' },
            { tr: 'kuş', en: 'bird' },
            { tr: 'balık', en: 'fish' },
            { tr: 'tavşan', en: 'rabbit' },
            { tr: 'hamster', en: 'hamster' },
            { tr: 'papağan', en: 'parrot' },
            { tr: 'kaplumbağa', en: 'turtle' },
            { tr: 'meyve', en: 'fruit' },
            { tr: 'elma', en: 'apple' },
            { tr: 'muz', en: 'banana' },
            { tr: 'portakal', en: 'orange' },
            { tr: 'üzüm', en: 'grape' },
            { tr: 'çilek', en: 'strawberry' },
            { tr: 'kiraz', en: 'cherry' },
            { tr: 'hayvan', en: 'animal' },
            { tr: 'aslan', en: 'lion' },
            { tr: 'fil', en: 'elephant' },
            { tr: 'zürafa', en: 'giraffe' },
            { tr: 'maymun', en: 'monkey' },
            { tr: 'zebra', en: 'zebra' },
            { tr: 'penguen', en: 'penguin' },
            { tr: 'yılan', en: 'snake' },
            { tr: 'timsah', en: 'crocodile' }
        ]
    },
    turkish: {
        easy: [ // Ünite 1-2-3
            { en: 'ambulans', tr: 'ambulance' },
            { en: 'balon', tr: 'balloon' },
            { en: 'bisküvi', tr: 'biscuit' },
            { en: 'kafe', tr: 'cafe' },
            { en: 'pasta', tr: 'cake' },
            { en: 'kamp', tr: 'camp' },
            { en: 'doktor', tr: 'doctor' },
            { en: 'elektronik posta', tr: 'e-mail' },
            { en: 'elektrik', tr: 'electrics' },
            { en: 'garaj', tr: 'garage' },
            { en: 'otel', tr: 'hotel' },
            { en: 'internet', tr: 'internet' },
            { en: 'dizüstü bilgisayar', tr: 'laptop' },
            { en: 'limon', tr: 'lemon' },
            { en: 'mikrofon', tr: 'microphone' },
            { en: 'not', tr: 'note' },
            { en: 'ofis', tr: 'office' },
            { en: 'piknik', tr: 'picnic' },
            { en: 'kısa sınav', tr: 'quiz' },
            { en: 'radyo', tr: 'radio' },
            { en: 'salata', tr: 'salad' },
            { en: 'sandviç', tr: 'sandwich' },
            { en: 'spor', tr: 'sport' },
            { en: 'durmak', tr: 'stop' },
            { en: 'süpermarket', tr: 'supermarket' }
        ],
        medium: [ // Ünite 4-5-6-7
            { en: 'sayılar', tr: 'numbers' },
            { en: 'renkler', tr: 'colors' },
            { en: 'kırmızı', tr: 'red' },
            { en: 'mavi', tr: 'blue' },
            { en: 'yeşil', tr: 'green' },
            { en: 'sarı', tr: 'yellow' },
            { en: 'siyah', tr: 'black' },
            { en: 'beyaz', tr: 'white' },
            { en: 'kahverengi', tr: 'brown' },
            { en: 'turuncu', tr: 'orange' },
            { en: 'mor', tr: 'purple' },
            { en: 'pembe', tr: 'pink' },
            { en: 'oyun alanı', tr: 'playground' },
            { en: 'salıncak', tr: 'swing' },
            { en: 'kaydırak', tr: 'slide' },
            { en: 'top', tr: 'ball' },
            { en: 'ip', tr: 'rope' },
            { en: 'koşmak', tr: 'run' },
            { en: 'zıplamak', tr: 'jump' },
            { en: 'oynamak', tr: 'play' },
            { en: 'vücut', tr: 'body' },
            { en: 'baş', tr: 'head' },
            { en: 'göz', tr: 'eye' }
        ],
        hard: [ // Ünite 8-9-10
            { en: 'evcil hayvan', tr: 'pet' },
            { en: 'kedi', tr: 'cat' },
            { en: 'köpek', tr: 'dog' },
            { en: 'kuş', tr: 'bird' },
            { en: 'balık', tr: 'fish' },
            { en: 'tavşan', tr: 'rabbit' },
            { en: 'papağan', tr: 'parrot' },
            { en: 'meyve', tr: 'fruit' },
            { en: 'elma', tr: 'apple' },
            { en: 'muz', tr: 'banana' },
            { en: 'portakal', tr: 'orange' },
            { en: 'üzüm', tr: 'grape' },
            { en: 'çilek', tr: 'strawberry' },
            { en: 'kiraz', tr: 'cherry' },
            { en: 'hayvan', tr: 'animal' },
            { en: 'aslan', tr: 'lion' },
            { en: 'fil', tr: 'elephant' },
            { en: 'zürafa', tr: 'giraffe' },
            { en: 'maymun', tr: 'monkey' },
            { en: 'zebra', tr: 'zebra' }
        ]
    }
};
